import { INDIAN_STATES } from './indian-states';

export type RegionKind = 'state' | 'province' | 'city';

export type CountryGeoConfig = {
  regionKind: RegionKind;
  regionLabel: string;
  regions: readonly string[];
};

const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
] as const;

const CANADA_PROVINCES = [
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland and Labrador',
  'Northwest Territories',
  'Nova Scotia',
  'Nunavut',
  'Ontario',
  'Prince Edward Island',
  'Quebec',
  'Saskatchewan',
  'Yukon',
] as const;

const AUSTRALIA_STATES = [
  'Australian Capital Territory',
  'New South Wales',
  'Northern Territory',
  'Queensland',
  'South Australia',
  'Tasmania',
  'Victoria',
  'Western Australia',
] as const;

const UK_REGIONS = ['England', 'Northern Ireland', 'Scotland', 'Wales'] as const;

const UAE_EMIRATES = [
  'Abu Dhabi',
  'Ajman',
  'Dubai',
  'Fujairah',
  'Ras Al Khaimah',
  'Sharjah',
  'Umm Al Quwain',
] as const;

const MALAYSIA_STATES = [
  'Johor',
  'Kedah',
  'Kelantan',
  'Kuala Lumpur',
  'Labuan',
  'Melaka',
  'Negeri Sembilan',
  'Pahang',
  'Penang',
  'Perak',
  'Perlis',
  'Putrajaya',
  'Sabah',
  'Sarawak',
  'Selangor',
  'Terengganu',
] as const;

const GERMANY_STATES = [
  'Baden-Württemberg',
  'Bavaria',
  'Berlin',
  'Brandenburg',
  'Bremen',
  'Hamburg',
  'Hesse',
  'Lower Saxony',
  'Mecklenburg-Vorpommern',
  'North Rhine-Westphalia',
  'Rhineland-Palatinate',
  'Saarland',
  'Saxony',
  'Saxony-Anhalt',
  'Schleswig-Holstein',
  'Thuringia',
] as const;

const BRAZIL_STATES = [
  'Acre',
  'Alagoas',
  'Amapá',
  'Amazonas',
  'Bahia',
  'Ceará',
  'Distrito Federal',
  'Espírito Santo',
  'Goiás',
  'Maranhão',
  'Mato Grosso',
  'Mato Grosso do Sul',
  'Minas Gerais',
  'Pará',
  'Paraíba',
  'Paraná',
  'Pernambuco',
  'Piauí',
  'Rio de Janeiro',
  'Rio Grande do Norte',
  'Rio Grande do Sul',
  'Rondônia',
  'Roraima',
  'Santa Catarina',
  'São Paulo',
  'Sergipe',
  'Tocantins',
] as const;

const MEXICO_STATES = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Ciudad de México',
  'Coahuila',
  'Colima',
  'Durango',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'México',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
] as const;

const PAKISTAN_PROVINCES = [
  'Azad Kashmir',
  'Balochistan',
  'Gilgit-Baltistan',
  'Islamabad Capital Territory',
  'Khyber Pakhtunkhwa',
  'Punjab',
  'Sindh',
] as const;

const BANGLADESH_DIVISIONS = [
  'Barishal',
  'Chattogram',
  'Dhaka',
  'Khulna',
  'Mymensingh',
  'Rajshahi',
  'Rangpur',
  'Sylhet',
] as const;

const NEPAL_PROVINCES = [
  'Bagmati',
  'Gandaki',
  'Karnali',
  'Koshi',
  'Lumbini',
  'Madhesh',
  'Sudurpashchim',
] as const;

const SRI_LANKA_PROVINCES = [
  'Central',
  'Eastern',
  'North Central',
  'Northern',
  'North Western',
  'Sabaragamuwa',
  'Southern',
  'Uva',
  'Western',
] as const;

const SOUTH_AFRICA_PROVINCES = [
  'Eastern Cape',
  'Free State',
  'Gauteng',
  'KwaZulu-Natal',
  'Limpopo',
  'Mpumalanga',
  'Northern Cape',
  'North West',
  'Western Cape',
] as const;

const SAUDI_REGIONS = [
  'Asir',
  'Eastern Province',
  'Hail',
  'Jazan',
  'Makkah',
  'Medina',
  'Najran',
  'Northern Borders',
  'Qassim',
  'Riyadh',
  'Tabuk',
] as const;

const CHINA_PROVINCES = [
  'Anhui',
  'Beijing',
  'Chongqing',
  'Fujian',
  'Gansu',
  'Guangdong',
  'Guangxi',
  'Guizhou',
  'Hainan',
  'Hebei',
  'Heilongjiang',
  'Henan',
  'Hong Kong',
  'Hubei',
  'Hunan',
  'Inner Mongolia',
  'Jiangsu',
  'Jiangxi',
  'Jilin',
  'Liaoning',
  'Macau',
  'Ningxia',
  'Qinghai',
  'Shaanxi',
  'Shandong',
  'Shanghai',
  'Shanxi',
  'Sichuan',
  'Tianjin',
  'Tibet',
  'Xinjiang',
  'Yunnan',
  'Zhejiang',
] as const;

const INDONESIA_PROVINCES = [
  'Aceh',
  'Bali',
  'Banten',
  'Central Java',
  'Central Kalimantan',
  'Central Sulawesi',
  'East Java',
  'East Kalimantan',
  'East Nusa Tenggara',
  'Jakarta',
  'Lampung',
  'Maluku',
  'North Sulawesi',
  'North Sumatra',
  'Papua',
  'Riau',
  'South Sulawesi',
  'South Sumatra',
  'West Java',
  'West Kalimantan',
  'West Nusa Tenggara',
  'West Papua',
  'West Sumatra',
  'Yogyakarta',
] as const;

const PHILIPPINES_REGIONS = [
  'Bicol',
  'Cagayan Valley',
  'Calabarzon',
  'Caraga',
  'Central Luzon',
  'Central Visayas',
  'Cordillera',
  'Davao',
  'Eastern Visayas',
  'Ilocos',
  'Metro Manila',
  'Mimaropa',
  'Northern Mindanao',
  'Soccsksargen',
  'Western Visayas',
  'Zamboanga Peninsula',
] as const;

const JAPAN_PREFECTURES = [
  'Aichi',
  'Akita',
  'Aomori',
  'Chiba',
  'Ehime',
  'Fukui',
  'Fukuoka',
  'Fukushima',
  'Gifu',
  'Gunma',
  'Hiroshima',
  'Hokkaido',
  'Hyogo',
  'Ibaraki',
  'Ishikawa',
  'Iwate',
  'Kagawa',
  'Kagoshima',
  'Kanagawa',
  'Kochi',
  'Kumamoto',
  'Kyoto',
  'Mie',
  'Miyagi',
  'Miyazaki',
  'Nagano',
  'Nagasaki',
  'Nara',
  'Niigata',
  'Oita',
  'Okayama',
  'Okinawa',
  'Osaka',
  'Saga',
  'Saitama',
  'Shiga',
  'Shimane',
  'Shizuoka',
  'Tochigi',
  'Tokushima',
  'Tokyo',
  'Tottori',
  'Toyama',
  'Wakayama',
  'Yamagata',
  'Yamaguchi',
  'Yamanashi',
] as const;

const ARGENTINA_PROVINCES = [
  'Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán',
] as const;

/** States, provinces, or emirates keyed by country name. */
export const COUNTRY_GEO: Record<string, CountryGeoConfig> = {
  India: { regionKind: 'state', regionLabel: 'State', regions: INDIAN_STATES },
  'United States': { regionKind: 'state', regionLabel: 'State', regions: US_STATES },
  Canada: { regionKind: 'province', regionLabel: 'Province', regions: CANADA_PROVINCES },
  Australia: { regionKind: 'state', regionLabel: 'State', regions: AUSTRALIA_STATES },
  'United Kingdom': { regionKind: 'state', regionLabel: 'Country', regions: UK_REGIONS },
  'United Arab Emirates': { regionKind: 'state', regionLabel: 'Emirate', regions: UAE_EMIRATES },
  Malaysia: { regionKind: 'state', regionLabel: 'State', regions: MALAYSIA_STATES },
  Germany: { regionKind: 'state', regionLabel: 'State', regions: GERMANY_STATES },
  Brazil: { regionKind: 'state', regionLabel: 'State', regions: BRAZIL_STATES },
  Mexico: { regionKind: 'state', regionLabel: 'State', regions: MEXICO_STATES },
  Pakistan: { regionKind: 'province', regionLabel: 'Province', regions: PAKISTAN_PROVINCES },
  Bangladesh: { regionKind: 'province', regionLabel: 'Division', regions: BANGLADESH_DIVISIONS },
  Nepal: { regionKind: 'province', regionLabel: 'Province', regions: NEPAL_PROVINCES },
  'Sri Lanka': { regionKind: 'province', regionLabel: 'Province', regions: SRI_LANKA_PROVINCES },
  'South Africa': { regionKind: 'province', regionLabel: 'Province', regions: SOUTH_AFRICA_PROVINCES },
  'Saudi Arabia': { regionKind: 'state', regionLabel: 'Region', regions: SAUDI_REGIONS },
  China: { regionKind: 'province', regionLabel: 'Province', regions: CHINA_PROVINCES },
  Indonesia: { regionKind: 'province', regionLabel: 'Province', regions: INDONESIA_PROVINCES },
  Philippines: { regionKind: 'province', regionLabel: 'Region', regions: PHILIPPINES_REGIONS },
  Japan: { regionKind: 'state', regionLabel: 'Prefecture', regions: JAPAN_PREFECTURES },
  Argentina: { regionKind: 'province', regionLabel: 'Province', regions: ARGENTINA_PROVINCES },
};

/** Major cities for countries without a state/province list. */
export const CITIES_BY_COUNTRY: Record<string, readonly string[]> = {
  Afghanistan: ['Herat', 'Jalalabad', 'Kabul', 'Kandahar', 'Mazar-i-Sharif'],
  Albania: ['Durrës', 'Elbasan', 'Shkodër', 'Tirana', 'Vlorë'],
  Algeria: ['Algiers', 'Annaba', 'Constantine', 'Oran', 'Sétif'],
  Austria: ['Graz', 'Innsbruck', 'Linz', 'Salzburg', 'Vienna'],
  Belgium: ['Antwerp', 'Brussels', 'Charleroi', 'Ghent', 'Liège'],
  Bhutan: ['Gelephu', 'Paro', 'Phuntsholing', 'Punakha', 'Thimphu'],
  Colombia: ['Barranquilla', 'Bogotá', 'Cali', 'Cartagena', 'Medellín'],
  Denmark: ['Aalborg', 'Aarhus', 'Copenhagen', 'Esbjerg', 'Odense'],
  Egypt: ['Alexandria', 'Cairo', 'Giza', 'Luxor', 'Port Said'],
  Finland: ['Espoo', 'Helsinki', 'Oulu', 'Tampere', 'Turku'],
  France: ['Bordeaux', 'Lille', 'Lyon', 'Marseille', 'Nice', 'Paris', 'Toulouse'],
  Greece: ['Athens', 'Heraklion', 'Larissa', 'Patras', 'Thessaloniki'],
  'Hong Kong': [
    'Central',
    'Kowloon',
    'New Territories',
    'Sha Tin',
    'Tsuen Wan',
    'Tuen Mun',
    'Wan Chai',
  ],
  Iran: ['Isfahan', 'Karaj', 'Mashhad', 'Shiraz', 'Tabriz', 'Tehran'],
  Iraq: ['Baghdad', 'Basra', 'Erbil', 'Kirkuk', 'Mosul', 'Najaf'],
  Ireland: ['Cork', 'Dublin', 'Galway', 'Limerick', 'Waterford'],
  Israel: ['Beer Sheva', 'Haifa', 'Jerusalem', 'Netanya', 'Tel Aviv'],
  Italy: ['Bologna', 'Florence', 'Milan', 'Naples', 'Rome', 'Turin', 'Venice'],
  Kenya: ['Eldoret', 'Kisumu', 'Mombasa', 'Nairobi', 'Nakuru'],
  Kuwait: ['Al Ahmadi', 'Al Farwaniyah', 'Hawalli', 'Kuwait City', 'Salmiya'],
  Maldives: ['Addu City', 'Fuvahmulah', 'Hulhumalé', 'Malé', 'Thinadhoo'],
  Netherlands: ['Amsterdam', 'Eindhoven', 'Rotterdam', 'The Hague', 'Utrecht'],
  'New Zealand': ['Auckland', 'Christchurch', 'Dunedin', 'Hamilton', 'Wellington'],
  Nigeria: ['Abuja', 'Ibadan', 'Kano', 'Lagos', 'Port Harcourt'],
  Norway: ['Bergen', 'Oslo', 'Stavanger', 'Trondheim', 'Tromsø'],
  Oman: ['Muscat', 'Nizwa', 'Salalah', 'Sohar', 'Sur'],
  Poland: ['Gdańsk', 'Kraków', 'Łódź', 'Poznań', 'Warsaw', 'Wrocław'],
  Portugal: ['Braga', 'Coimbra', 'Faro', 'Lisbon', 'Porto'],
  Qatar: ['Al Khor', 'Al Wakrah', 'Doha', 'Dukhan', 'Lusail'],
  Russia: ['Kazan', 'Moscow', 'Novosibirsk', 'Saint Petersburg', 'Yekaterinburg'],
  Singapore: ['Bedok', 'Bukit Merah', 'Jurong East', 'Singapore', 'Tampines', 'Woodlands'],
  'South Korea': ['Busan', 'Daegu', 'Daejeon', 'Gwangju', 'Incheon', 'Seoul'],
  Spain: ['Barcelona', 'Bilbao', 'Madrid', 'Seville', 'Valencia', 'Zaragoza'],
  Sweden: ['Gothenburg', 'Malmö', 'Stockholm', 'Uppsala', 'Västerås'],
  Switzerland: ['Basel', 'Bern', 'Geneva', 'Lausanne', 'Zurich'],
  Thailand: ['Bangkok', 'Chiang Mai', 'Hat Yai', 'Khon Kaen', 'Pattaya', 'Phuket'],
  Turkey: ['Ankara', 'Antalya', 'Bursa', 'Istanbul', 'Izmir', 'Konya'],
  Vietnam: ['Can Tho', 'Da Nang', 'Haiphong', 'Hanoi', 'Ho Chi Minh City', 'Nha Trang'],
};
